Repository metal3-io/metal3-io.github.io, pull requests merged in 2019-10, with the labels that each got.

#99 Add OWNERS file.
  OWNERS
Labels: size/S

#100 Update docs for Ironic
  _includes/try-it.md
Labels: approved, lgtm, size/M

#101 Update docs to just use clouds.yaml in metal3-dev-env repo
  _includes/try-it.md
Labels: approved, lgtm, size/M

#104 Add a table explaining metal3-dev-env configuration options
  _includes/try-it.md
Labels: lgtm, size/M
