Repository metal3-io/metal3-io.github.io, pull requests merged in 2019-11, with the labels that each got.

#105 adding blogpost about the conference OpenStack-Ironic-and-Bare-Metal-…
  _includes/docs.md
  _posts/2019-10-31-OpenStack-Ironic-and-Bare-Metal-Infrastructure_All-Abstractions-Start-Somewhere.md
Labels: approved, lgtm, size/S

#106 Video blogpost about the kni managed baremetal talk at Red Hat summit 2019
  _includes/docs.md
  _posts/2019-11-07-Kubernetes-native_Infrastructure-Managed_Baremetal_with_Kubernetes_Operators_and_OpenStack_Ironic.md
Labels: approved, size/S

#107 Blogpost extend datacenter summit 2019
  _includes/docs.md
  _posts/2019-11-13-Extend_Your_Data_Center_to_the_Hybrid_Edge-Red_Hat_Summit.md
Labels: approved, lgtm, size/S

#111 [blog] Fix some typos
  _posts/2019-11-13-Extend_Your_Data_Center_to_the_Hybrid_Edge-Red_Hat_Summit.md
Labels: approved, lgtm, size/XS
