Repository metal3-io/metal3-io.github.io, pull requests merged in 2019-12, with the labels that each got.

#112 Metal3 kubecon 2k19 blogpost
  _includes/docs.md
  _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
Labels: approved, lgtm, size/M

#114 The new stack blogpost
  _includes/docs.md
  _posts/2019-05-13-The_new_stack_Metal3_Uses_OpenStack_Ironic_for_Declarative_Bare_Metal_Kubernetes.md
Labels: approved, lgtm, size/M

#116 fixes recent entries spacing
  _includes/related-entries.html
  _sass/_subpage.scss
Labels: approved, lgtm, size/S

#109 Modify OWNERS to define labels
  OWNERS
Labels: approved, lgtm, size/M

#118 Update try-it
  _includes/try-it.md
Labels: approved, lgtm, size/L

#117 blogpost Raise_some_horns_Red_Hat_s_MetalKube_aims_to_make_Kubernetes…
  _includes/docs.md
  _posts/2019-04-12-Raise_some_horns_Red_Hat_s_MetalKube_aims_to_make_Kubernetes_on_bare_machines_simple.md
Labels: approved, lgtm, size/M
