Repository metal3-io/metal3-io.github.io, pull requests merged in 2020-02, with the labels that each got.

#131 Add slack notifications
  .travis.yml
Labels: approved, lgtm, size/S

#132 Notify on failures/changes
  .travis.yml
Labels: approved, lgtm, size/XS

#133 Never notify on success
  .travis.yml
Labels: approved, lgtm, size/XS

#126 Add spacing in headers
  _includes/blog-aside.html
  _includes/docs.md
  _includes/metas-ogp.html
  _layouts/post.html
  index.html
Labels: approved, lgtm, size/S

#134 Add new environment variables
  _includes/try-it.md
Labels: approved, lgtm, size/XS

#136 Update try-it.md based on merged PR#216
  _includes/try-it.md
Labels: approved, lgtm, size/XS

#138 Generate pages via travis
  .travis.yml
Labels: approved, size/S

#139 Add back admonitions (restore old PR reverted)
  Gemfile
  _config.yml
  _includes/head.html
  _layouts/default.html
  _posts/2019-09-11-Baremetal-operator.md
  _sass/_premonition.scss
  _sass/styles.scss
Labels: approved, size/M

#140 Replace docker by podman when building the web locally
  README.md
Labels: approved, lgtm, size/XS

#141 Add search
  _config.yml
  _includes/header.html
  _layouts/search.html
  _sass/_autocomplete.scss
  _sass/_inputs.scss
  _sass/styles.scss
  assets/js/lunr.min.js
  search.html
Labels: approved, lgtm, size/XXL

#110 Addalosada
  OWNERS
Labels: approved, lgtm, size/XS

#135 New blog post: A detailed walkthrough the installation of the metal3-dev-env
  _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
  assets/2020-02-18-metal3-dev-env-install-deep-dive/metal3-dev-env.resized.png
Labels: approved, lgtm, size/XL

#143 Blog post: Metal³: Kubernetes Native Bare Metal Cluster Management
  _posts/2020-02-27-talk-kubernetes-finland-metal3.md
  assets/2020-02-27-talk-kubernetes-finland-metal3/metal3-crds-controllers.resized.png
  assets/2020-02-27-talk-kubernetes-finland-metal3/metal3-instrospection.resized.png
  assets/2020-02-27-talk-kubernetes-finland-metal3/metal3-provisioning.resized.png
Labels: approved, blog, lgtm, size/M

#130 Update try-it document
  _includes/try-it.md
  assets/images/metal3-dev-env.svg
Labels: approved, kind/documentation, lgtm, size/L

#145 Add copy button to block codes
  _includes/footer.html
  _includes/header.html
  _sass/_syntax.scss
  _sass/styles.scss
  assets/js/clipboard.min.js
  assets/js/copy.js
Labels: approved, lgtm, size/M

#144 Add PhotoSwipe gallery support
  _includes/head.html
  _includes/header.html
  _layouts/post.html
  assets/js/photoswipe-page.js
Labels: approved, lgtm, size/L

#142 Add formatting changes for tags/admonitions
  CNAME
  GUIDELINES.md
  README.md
  _faqs/baremetal-operator.md
  _faqs/ipmi.md
  _faqs/out-of-band.md
  _faqs/what-is-an-operator.md
  _includes/blog-aside.html
  _includes/docs.md
  _includes/privacy-statement.md
  _includes/related-entries.html
  _includes/try-it.md
  _posts/2019-04-12-Raise_some_horns_Red_Hat_s_MetalKube_aims_to_make_Kubernetes_on_bare_machines_simple.md
  _posts/2019-04-30-Metal-Kubed-Baremetal-Provisioning-for-Kubernetes.md
  _posts/2019-05-13-The_new_stack_Metal3_Uses_OpenStack_Ironic_for_Declarative_Bare_Metal_Kubernetes.md
  _posts/2019-06-25-Metal3.md
  _posts/2019-09-11-Baremetal-operator.md
  _posts/2019-10-31-OpenStack-Ironic-and-Bare-Metal-Infrastructure_All-Abstractions-Start-Somewhere.md
  _posts/2019-11-07-Kubernetes-native_Infrastructure-Managed_Baremetal_with_Kubernetes_Operators_and_OpenStack_Ironic.md
  _posts/2019-11-13-Extend_Your_Data_Center_to_the_Hybrid_Edge-Red_Hat_Summit.md
  _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
  _posts/2020-01-20-metal3_deploy_kubernetes_on_bare_metal.md
  _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
  _sass/_footer.scss
  _sass/_functions.scss
  _sass/_global.scss
  _sass/_header.scss
  _sass/_homepage.scss
  _sass/_reset.scss
  _sass/_subpage.scss
  _sass/_type.scss
  _sass/_variables.scss
  _sass/print.scss
  assets/css/styles.scss
  assets/images/home-left-image.svg
  assets/images/home-right-image.svg
  assets/images/infograph-stack.svg
  assets/images/server-stacks.svg
  blog/categories.html
  blog/index.html
  documentation.html
  index.html
  privacy-statement.html
  try-it.html
Labels: approved, lgtm, size/XXL

#146 Update try-it based on PR#229 in metal3-dev-env
  _includes/try-it.md
Labels: approved, lgtm, size/XS

#147 Document how to use gallery
  GUIDELINES.md
Labels: approved, lgtm, size/M

#148 Disable line numbers
  _config.yml
  assets/js/copy.js
Labels: approved, lgtm, size/S

#149 Use try-it as a full-featured markdown file
  _layouts/tryit.html
  try-it.html
  try-it.md
Labels: approved, lgtm, size/L

#151 Add site verification
  _includes/head.html
Labels: approved, lgtm, size/XS
