Repository metal3-io/metal3-io.github.io, pull requests merged in 2020-03, with the labels that each got.

#154 Bump premonition version so that it works also on columns different t…
  Gemfile
Labels: approved, lgtm, size/XS

#156 Fix container name
  README.md
Labels: approved, lgtm, size/XS

#158 Ignore youtube links on linkchecker
  Rakefile
Labels: approved, lgtm, size/XS

#157 Use - instead of spaces for links
  _layouts/post.html
Labels: approved, size/XS

#159 Use - for categories with spaces
  _includes/blog-aside.html
Labels: approved, lgtm, size/XS

#153 Rename CAPBM to CAPM3
  _includes/docs.md
  _posts/2020-03-05-CAPI_provider_renaming.md
  try-it.md
Labels: size/M

#160 Use slugify
  _includes/blog-aside.html
  try-it.md
Labels: approved, size/M

#161 Rename header reference from CAPBM to CAPM3
  try-it.md
Labels: approved, lgtm, size/XS

#162 Update default CAPI version based on #243
  try-it.md
Labels: approved, lgtm, size/XS

#163 fixing possible xss attack through the search results page
  _layouts/search.html
Labels: approved, lgtm, size/XS

#164 Add spellchecking of commits via pre-commit and CI
  .pre-commit-config.yaml
  .travis.yml
  .yaspellerrc
  GUIDELINES.md
  _config.yml
  _includes/docs.md
  _posts/2019-04-12-Raise_some_horns_Red_Hat_s_MetalKube_aims_to_make_Kubernetes_on_bare_machines_simple.md
  _posts/2019-05-13-The_new_stack_Metal3_Uses_OpenStack_Ironic_for_Declarative_Bare_Metal_Kubernetes.md
  _posts/2019-06-25-Metal3.md
  _posts/2019-10-31-OpenStack-Ironic-and-Bare-Metal-Infrastructure_All-Abstractions-Start-Somewhere.md
  _posts/2019-11-07-Kubernetes-native_Infrastructure-Managed_Baremetal_with_Kubernetes_Operators_and_OpenStack_Ironic.md
  _posts/2019-11-13-Extend_Your_Data_Center_to_the_Hybrid_Edge-Red_Hat_Summit.md
  _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
  _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
  _posts/2020-02-27-talk-kubernetes-finland-metal3.md
  _posts/2020-03-05-CAPI_provider_renaming.md
  assets/images/metal3-dev-env.svg
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#165 Update try-it based on #250 in Metal3-dev-env
  try-it.md
Labels: approved, lgtm, size/XS

#166 Rename json file for easier recognition of editors
  .pre-commit-config.yaml
  .yaspeller.json
Labels: approved, lgtm, size/S

#168 Replace video links from my personal account to metal3 youtube account
  _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
Labels: approved, lgtm, size/XS

#170 Fix existing typos in try-it.md
  try-it.md
Labels: approved, lgtm, size/S

#171 Ignore 429 errors on html-proofer
  Rakefile
Labels: approved, lgtm, size/XS

#167 Point to yaspeller upstream repo for pre-commit plugin
  .pre-commit-config.yaml
  .yaspeller.json
Labels: approved, lgtm, size/S
