Repository metal3-io/metal3-io.github.io, pull requests merged in 2020-07, with the labels that each got.

#183 add stbenjam and maelk as approvers for blog posts
  OWNERS
Labels: approved, lgtm, size/S

#181 Add a new blog post presenting raw image streaming
  .yaspeller.json
  _posts/2020-07-05-raw-image-streaming.md
Labels: approved, lgtm, size/L

#178 Metal3 development environment deep dive part 2: Deploying a new baremetal cluster
  .yaspeller.json
  _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
  assets/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment/manifest-directory.png
  assets/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment/metal3-bmetal-arch-overview.png
  assets/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment/metal3-generate-templates.png
Labels: approved, lgtm, size/L

#180 Update quick-start page
  try-it.md
Labels: approved, lgtm, size/S

#184 Update owners to reflect team changes
  OWNERS
Labels: approved, lgtm, size/XS

#182 Add a blog post introducing the IPAM controller
  .yaspeller.json
  _posts/2020-07-06-IP_address_manager.md
Labels: approved, lgtm, size/L

#187 Update variable CAPI_VERSION to CAPM3_VERSION
  _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
  _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
  try-it.md
Labels: approved, lgtm, size/M
