Repository metal3-io/metal3-io.github.io, pull requests merged in 2020-09, with the labels that each got.

#188 Reflect refactoring changes in metal3-dev-env
  _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
  try-it.md
Labels: approved, lgtm, size/M

#190 Add note regarding redeploying metal3-dev-env
  try-it.md
Labels: approved, lgtm, size/XS

#185 Update try-it page
  assets/images/metal3-dev-env.svg
  try-it.md
Labels: approved, lgtm, size/L

#186 Update try-it.md with ironic-client
  try-it.md
Labels: approved, lgtm, size/S

#191 Add CNCF notice to the site footer
  .travis.yml
  _includes/footer.html
  _posts/2019-06-25-Metal3.md
  assets/images/cncf-color.png
  assets/images/cncf-color.svg
Labels: approved, lgtm, size/XS

#194 footer: Add Linux Foundation footer
  _includes/footer.html
  _sass/_footer.scss
Labels: approved, lgtm, size/XS

#195 Limit the number of blog posts highligted in the home page
  Gemfile
  index.html
Labels: approved, lgtm, size/XS
