Repository metal3-io/metal3-io.github.io, pull requests merged in 2020-01, with the labels that each got.

#120 Use full URL for og image
  _includes/metas-ogp.html
Labels: approved, size/XS

#121 Add miniatures to screen videos
  _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
Labels: approved, lgtm, size/S

#123 Update to latest code for DTM -> DPAL transition for analytics
  _includes/footer.html
  _includes/head.html
Labels: approved, lgtm, size/S

#122 yolanda's shift dev video blogpost
  _includes/docs.md
  _posts/2020-01-20-metal3_deploy_kubernetes_on_bare_metal.md
Labels: approved, lgtm, size/S

#127 Update link to relocated project-infra
  community-resources.html
Labels: approved, kind/bug, lgtm, size/XS
