Repository metal3-io/metal3-io.github.io, pull requests merged in 2021-05, with the labels that each got.

#203 Update Rakefile
  Rakefile
Labels: size/M

#204 build(precommit-config): updates precommit config to later modules
  .pre-commit-config.yaml
Labels: approved, lgtm, size/L

#205 Precommit apply
  _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
  _posts/2020-07-05-raw-image-streaming.md
  _posts/2020-07-06-IP_address_manager.md
  assets/images/cncf-color.svg
  assets/images/metal3-dev-env.svg
  assets/js/clipboard.min.js
  assets/js/copy.js
  assets/js/lunr.min.js
  assets/js/photoswipe-page.js
  try-it.md
Labels: approved, lgtm, size/XXL

#206 Remove travis
  .github/dependabot.yml
  .github/workflows/broken-link-check.yml
  .github/workflows/jekyll.yml
  .travis.yml
Labels: approved, lgtm, size/M

#207 Add fmuyassarov as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#200 Update OWNERS to reflect team changes
  OWNERS
Labels: approved, lgtm, size/XS

#202 Update try-it guide to refer v1alpha4 instead of v1alpha3
  _posts/2019-06-25-Metal3.md
  try-it.md
Labels: approved, lgtm, ok-to-test, size/L

#197 Add pivoting blog
  .yaspeller.json
  _posts/2021-05-05-Pivoting.md
Labels: approved, blog, lgtm, size/L

#214 Update try it guide
  .yaspeller.json
  try-it.md
Labels: approved, lgtm, size/M
