Repository metal3-io/metal3-io.github.io, pull requests merged in 2023-08, with the labels that each got.

#341 New Contributor page
  _includes/header.html
  _sass/_header.scss
  contribute.html
Labels: size/S, lgtm, approved

#342 How to Contribute section
  _includes/docs.md
  contribute.html
Labels: size/M, lgtm, approved

#344 Small updates to try it
  try-it.md
Labels: size/S, lgtm, approved

#343 Search bar fix
  _includes/header.html
  _sass/_header.scss
Labels: size/M, lgtm, approved

#349 Links update and deleted files
  _includes/header.html
  _layouts/tryit.html
  index.html
  try-it.md
Labels: lgtm, approved, size/XL
