Repository metal3-io/metal3-io.github.io, pull requests merged in 2023-09, with the labels that each got.

#351 Add pre-commit workflow
  .github/workflows/pre-commit.yml
  .yaspeller.json
  GUIDELINES.md
  OWNERS
  SECURITY_CONTACTS
  _includes/docs.md
  _includes/footer.html
  _includes/header.html
  _sass/_header.scss
  _sass/_homepage.scss
  assets/images/youtube.svg
  community-resources.html
  contribute.html
  index.html
Labels: lgtm, approved, size/L

#346 Repostioned footer links for mobile
  _includes/footer.html
  _sass/_footer.scss
Labels: size/M, lgtm, approved

#357 Fix trailing whitespace
  _includes/footer.html
Labels: lgtm, approved, size/XS

#359 improve pre-commit workflow
  .github/workflows/pre-commit.yml
Labels: lgtm, approved, size/XS

#361 run dependabot less often
  .github/dependabot.yml
Labels: lgtm, approved, size/XS

#363 Dark mode feature
  _includes/footer.html
  _includes/header.html
  _sass/_footer.scss
  assets/images/cncf-white.svg
  assets/images/moon-outline.png
  assets/images/moon.png
  assets/images/sprite.svg
Labels: lgtm, approved, size/L
