Repository metal3-io/metal3-io.github.io, pull requests merged in 2024-01, with the labels that each got.

#379 Update yaspeller to latest version
  .pre-commit-config.yaml
  .yaspeller.json
Labels: lgtm, approved, size/XS

#381 remove yaspeller
  .pre-commit-config.yaml
  .travis.yml
  .yaspeller.json
  GUIDELINES.md
  package-lock.json
  package.json
Labels: lgtm, approved, size/XXL

#389 add Salima's blog post on Jekyll
  _posts/2024-01-18-How_to_run_Metal3_website_locally_with_Jekyll.md
Labels: size/M, lgtm, approved

#391 add cspell as new spell checker
  .cspell-config.json
  _posts/2019-04-12-Raise_some_horns_Red_Hat_s_MetalKube_aims_to_make_Kubernetes_on_bare_machines_simple.md
  _posts/2019-11-13-Extend_Your_Data_Center_to_the_Hybrid_Edge-Red_Hat_Summit.md
  _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
  _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
  hack/spellcheck.sh
Labels: lgtm, approved, size/XL

#392 simplify OWNERS
  OWNERS
Labels: size/M, lgtm, approved

#393 cleanup ignored words list
  .cspell-config.json
Labels: lgtm, approved, size/L
