Repository metal3-io/metal3-io.github.io, pull requests merged in 2024-12, with the labels that each got.

#529 :seedling: Add more links to ignore file
  .lycheeignore
Labels: lgtm, approved, size/XS

#532 add auto (re)approver workflow
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: size/M, lgtm, approved

#535 :bug: Fix/ignore broken links
  .lycheeignore
  _posts/2019-06-25-Metal3.md
  _posts/2019-11-13-Extend_Your_Data_Center_to_the_Hybrid_Edge-Red_Hat_Summit.md
Labels: size/S, lgtm, approved

#536 Post: Introducing BMO e2e
  .cspell-config.json
  _posts/2024-12-12-Introducing-BMO-E2E.md
Labels: lgtm, approved, size/L
