Repository metal3-io/metal3-io.github.io, pull requests merged in 2024-06, with the labels that each got.

#446 Add more approvers and reviewers
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#444 Add Makefile for linting and serving
  Makefile
  README.md
  hack/pre-commit.sh
Labels: size/M, lgtm, approved

#442 Post: Scaling part 3
  _posts/2024-05-30-Scaling_part_3.md
  assets/2024-05-30-Scaling_part_3/CAPI-dashboard.png
  assets/2024-05-30-Scaling_part_3/KCP-profiling.png
Labels: lgtm, approved, size/L

#443 shellcheck only files
  hack/shellcheck.sh
Labels: lgtm, approved, size/XS

#447 Standardize metal3 pronunciation
  documentation.html
  index.html
Labels: lgtm, approved, size/XS
